os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
install:
  - ./bootstrap/install-deps-${TRAVIS_OS_NAME}.sh
script: ./autogen.sh && ./configure && make distcheck -j 2
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - tommy@monetas.net
  email:
    on_success: change
    on_failure: always
  irc:
    on_success: change
    on_failure: always
    channels:
      - "chat.freenode.net#opentransactions"
    template:
      - "%{branch} (%{commit} - %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build: %{build_url}"
