os:
- linux
- osx
language: cpp
compiler:
- gcc
- clang
install: ./scripts/travis/install-deps.sh "${TRAVIS_OS_NAME}"
before_script:
- ./scripts/travis/cppcheck_wrapper.sh ./src
- ./scripts/travis/cppcheck_wrapper.sh -I./include/opentxs/api/ -I./include/opentxs/core/ -I./include/opentxs/ext/ --suppress=passedByValue --suppress=unnecessaryQualification --suppress=noConstructor --suppress=variableScope --suppress=operatorEq --suppress=unusedPrivateFunction --suppress=noCopyConstructor ./src/api/
- ./scripts/travis/clang-format-checker.sh
script:
- mkdir build
- cd build
- cmake .. && make -j 2 && make test
- cd ..
branches:
  only:
  - master
  - develop
before_deploy: ./scripts/travis/build_tar.sh "${TRAVIS_OS_NAME}"
deploy:
  provider: s3
  access_key_id: AKIAIR7XPKSU5OIGJ5IA
  secret_access_key:
    secure: FvR6JgcTeINRq4df75oaeirenrwnjc5jTMEojeHVxDMXWIDzFRWN51tie1TnKCbxZcehtw/fQFDjFT+Uktm0QvyzPcbpxI92JQt+cW1Nu+f5FKmsl795apU6sXAqSGI9fYzooUdfJHB4VMjv5vKun8OdXJY87WmvY6wYYUZhjiw=
  bucket: monetas-builds
  skip_cleanup: true
  local-dir: s3
  upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}
  on:
    branch: ${TRAVIS_BRANCH}
