language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install libprotobuf-dev protobuf-compiler libzmq3-dev
  - git clone https://github.com/zeromq/cppzmq.git
  - sudo cp cppzmq/zmq.hpp /usr/local/include/
script: ./autogen.sh && ./configure && make
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - tommy@monetas.net
  email:
    on_success: change
    on_failure: always
