name: Blockchain

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-20.04, windows-2019, macos-10.15]
        include:
          - platform: 'ubuntu-20.04'
            vcpkg_triplet: 'x64-linux'
            cmake_extra: '-DOPENTXS_BUILD_TESTS=OFF'
          - platform: 'macos-10.15'
            vcpkg_triplet: 'x64-osx'
            cmake_extra: '-DOPENTXS_BUILD_TESTS=ON'
          - platform: 'windows-2019'
            vcpkg_triplet: 'x64-windows'
            cmake_extra: '-DOPENTXS_BUILD_TESTS=ON -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded" -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib" -DCMAKE_STATIC_LINKER_FLAGS="/NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib"'
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Install extra dependencies
      if: matrix.platform == 'ubuntu-20.04'
      run: |
          sudo apt-get update
          sudo apt-get install -y autoconf autopoint curl g++ git gperf libgl1-mesa-dev libglu1-mesa-dev libtool libx11-dev libx11-xcb-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxext-dev libxi-dev libxkbcommon-x11-dev libxrender-dev make pkg-config python3 tar unzip zip
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.18.4'
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v5
      with:
        vcpkgArguments: '--triplet ${{ matrix.vcpkg_triplet }} --overlay-ports=${{ github.workspace }}/vcpkg/ports --overlay-triplets=${{ github.workspace }}/vcpkg/triplets @${{ github.workspace }}/vcpkg/vcpkg.txt'
        vcpkgDirectory: '${{ github.workspace }}/deps/vcpkg'
    - name: 'Compile'
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        vcpkgTriplet: '${{ matrix.vcpkg_triplet }}'
        buildDirectory: '${{ github.workspace }}/build'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Release -DOT_USE_VCPKG_TARGETS=ON -DOT_INSTALL_LIBRARY_DEPENDENCIES=OFF -DOT_WITH_BLOCKCHAIN=ON -DOT_WITH_QT=ON -DOT_ENABLE_RPC=OFF ${{ matrix.cmake_extra }}'
        buildWithCMake: true
        buildWithCMakeArgs: '-- -k 0'
