name: Desktop

on: [push, pull_request]

env:
    VCPKG_COMMIT: 6185aa76504a5025f36754324abf307cc776f3da

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]
        include:
          - platform: 'ubuntu-18.04'
            vcpkg_triplet: 'x64-linux'
          - platform: 'ubuntu-20.04'
            vcpkg_triplet: 'x64-linux'
          - platform: 'macos-10.15'
            vcpkg_triplet: 'x64-osx'
          - platform: 'windows-2019'
            vcpkg_triplet: 'x64-windows-static'
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      with:
        path: ${{ runner.temp }}/vcpkg
        key: ${{ env.VCPKG_COMMIT }}-${{ hashFiles('vcpkg/vcpkg.txt') }}-${{ matrix.platform }}
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v1
      with:
        vcpkgArguments: '--triplet ${{ matrix.vcpkg_triplet }} --overlay-ports=${{ github.workspace }}/vcpkg/ports @${{ github.workspace }}/vcpkg/vcpkg.txt'
        vcpkgDirectory: '${{ runner.temp }}/vcpkg'
        vcpkgGitCommitId: '${{ env.VCPKG_COMMIT }}'
    - name: Upgrade to gcc/g++ 8
      if: matrix.platform == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-8 g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
    - name: 'Compile'
      if: matrix.platform != 'windows-2019'
      uses: lukka/run-cmake@v1
      with:
        cmakeGenerator: ${{ matrix.cmake_generator }}
        cmakeBuildType: 'Release'
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        vcpkgTriplet: '${{ matrix.vcpkg_triplet }}'
        buildDirectory: '${{ github.workspace }}/build'
        cmakeAppendedArgs: '-GNinja -DOPENTXS_BUILD_TESTS=ON -DOT_STORAGE_FS=ON -DOT_STORAGE_SQLITE=ON -DOT_CRYPTO_SUPPORTED_KEY_RSA=ON -DOT_WITH_BLOCKCHAIN=ON -DOT_CASH_USING_LUCRE=ON -DOT_USE_VCPKG_TARGETS=ON'
        buildWithCMake: true
#    - name: Run unit tests
#      if: matrix.platform != 'windows-2019'
#      run: |
#        cd '${{ github.workspace }}/build'
#        ctest -j2 --repeat until-pass:3 --schedule-random
